# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:30
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_topping_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
